server:
  port: 1223

# MYSQL
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${SECURITY_DB_IP:localhost}:${SECURITY_DB_PORT:3306}/springbootsecurityexample
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
